name: hng_boilerplate

services:
  nginx:
    image: nginx:stable-alpine3.19
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hng-network

networks:
  hng-network:
    driver: bridge
