name: hng_boilerplate

services:
  app:
    build:
      context: .
    container_name: app
    networks:
      - hng-network
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.12
    container_name: db
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_NAME?Variable not set}
    ports:
      - "5432:5432"
    networks:
      - hng-network

  nginx:
    image: nginx:stable-alpine3.19
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - hng-network

volumes:
  pg-data:

networks:
  hng-network:
    driver: bridge
