name: hng_boilerplate

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    networks:
      - hng-network
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env.production
    depends_on:
      - db

  db:
    image: postgres:14.12
    container_name: db
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env.production
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_NAME?Variable not set}
    networks:
      - hng-network

volumes:
  pg-data:

networks:
  hng-network:
    driver: bridge
