name: Main Branch Deployment

on:
  workflow_run:
    workflows: ["CIDEV"]
    types:
      - completed


jobs:
  access_server:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use SSH Action
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd hng_boilerplate_python_fastapi_web
            git pull origin dev
            docker compose -f docker-compose.nginx.yml up --build -d
            docker compose -f docker-compose.dev.yml --env-file .env.development up --build -d --remove-orphans
            docker system prune -f
