name: Main Branch Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [dev]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use SSH Action
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd hng_boilerplate_python_fastapi_web
            git pull origin dev
            docker compose -f docker-compose.nginx.yml up --build -d
            docker compose -f docker-compose.dev.yml --env-file .env.development up --build -d --remove-orphans
            docker system prune -f
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
