name: CIPROD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          virtual-environment: venv

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Copy  env file
        run: cp .env.production .env

      - name: Run migrations
        run: |
          activate
          alembic upgrade head

      - name: Run tests
        run: |
          activate
          pytest
